### ISSUE TITLE
Should "Infix" be "Prefix"?

### ISSUE THREAD

**Issue by pmetzger** [aryx/yacfe#11]
The type `expressionbis` defined in `ast_c.ml` (whose name I find mysterious — why is it called `expressionbis`? something to do with the fact that `expression` is wrapped?) defines:

```
  | Postfix        of expression * fixOp
  | Infix          of expression * fixOp
```

So far as I can tell, "Infix" should be "Prefix", given its use in the grammar (see `parser_c.mly`). Am I correct on this?

(Also, `fixOp` seems like a bad name. Would something like `incrOp` be better, even though there's also decrementation?)

**Comment by pmetzger** [comment]
I also must confess I find the names of some other tokens mysterious, like: (taken from `lexer_c.mll`):

```
  | ">=" { TSupEq(tokinfo lexbuf) } | "<=" { TInfEq(tokinfo lexbuf) }
  | "<"  { TInf(tokinfo lexbuf) }   | ">"  { TSup(tokinfo lexbuf) }
```

and

```
  | ";"    { TPtVirg(tokinfo lexbuf) }
```

**Comment by aryx** [comment]
It's french ...

TPtVirg means Token Point Virgule (virgule means comma so point virgule
means semi colon).
Sup means superior (>) Inf means Inferior (<)
Eq means equal

**Comment by aryx** [comment]
Yes it should be Prefix. fixOp could be renamed incrOp.
bis means "again" because I had to invent another type name that is
related to expression. It could be expression_kind.

**Comment by pmetzger** [comment]
Would you object to these being converted to things like TSemi for ";", TLt for "<", etc? (I would understand if you object, but I find some of this a bit unnatural.)

**Comment by aryx** [comment]
Sure, no problem.

**Comment by pmetzger** [comment]
I've now submitted PR #12 which fixes this stuff.

**Comment by pmetzger** [comment]
As #12 has been merged, I'll close this.
